### ISSUE TITLE
seneca-web.js produces error

### ISSUE THREAD

**Issue by jackrobson** [PacktPublishing/Developing-Microservices-With-Nodejs#1]
/Users/jack/Sites/microservices_book/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
    ^

TypeError: app.use() requires middleware functions
    at Function.use (/Users/jack/Sites/microservices_book/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/Users/jack/Sites/microservices_book/index.js:18:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
jack:microservices_book jack$ ç

**Comment by janlukasschroeder** [comment]
Did you try this: http://stackoverflow.com/questions/39480013/app-use-requires-middleware-functions-app-use-seneca-exportweb
